version: 0118.1H.1-LHLF-2030-100p
logging_level: INFO
foresight: myopic
using_single_node: false
single_node_province: Shandong
results_dir: results/
summary_dir: summary/
threads: 40
mem_per_thread: 15000
tmin: -01-01 00:00
tmax: -12-31 23:00
freq: 1h
add_aluminum: true
only_other_load: true
iterative_optimization: true
aluminum_commitment: false
aluminum_max_iterations: 3
aluminum_convergence_tolerance: 0.001
aluminum_parallel: true
aluminum_max_workers: 25
aluminum_capacity_ratio: 1.0
scenario:
  line_limits:
  - opt
  pathway:
  - linear2050
  topology: current+FCG
  planning_horizons:
  - 2030
  co2_reduction:
    linear2060:
      '2020': -1.0
      '2025': -1.0
      '2030': 0.143
      '2035': 0.286
      '2040': 0.429
      '2045': 0.571
      '2050': 0.714
      '2055': 0.857
      '2060': 1.0
    linear2050:
      '2020': -1.0
      '2025': -1.0
      '2030': 0.2
      '2035': 0.4
      '2040': 0.6
      '2045': 0.8
      '2050': 1.0
      '2055': 1.0
      '2060': 1.0
  opts:
  - ll
  attr: p_nom
  heating_demand:
  - positive
solving:
  solver:
    name: gurobi
    options: default
  solver_options:
    default:
      Threads: 192
      Crossover: 0
      Method: 2
      BarConvTol: 1.0e-05
      FeasibilityTol: 1.0e-06
      AggFill: 0
      PreDual: 0
      GURO_PAR_BARDENSETHRESH: 200
      DualReductions: 0
      OutputFlag: 1
      LogToConsole: 1
      LogFile: ''
    MILP:
      Threads: 192
      Method: -1
      MIPGap: 0.01
      TimeLimit: 7200
      Heuristics: 0.5
      Cuts: 0
      Presolve: -1
  options:
    track_iterations: false
    min_iterations: 4
    max_iterations: 6
    skip_iterations: false
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: false
    clip_p_max_pu: 0.01
  mem: 150000
aluminum:
  grid_interaction:
    '2020': false
    '2025': false
    '2030': true
    '2035': true
    '2040': true
    '2045': true
    '2050': true
    '2055': true
    '2060': true
  capacity_ratio: 1.0
  scenario_dimensions:
    smelter_flexibility:
      low:
        p_min_pu: 0.99
        restart_cost: 96593.79766
        stand_by_cost: 1.2
      mid:
        p_min_pu: 0.9
        restart_cost: 13980.68124
        stand_by_cost: 1.2
      high:
        p_min_pu: 0.7
        restart_cost: 2796.136248
        stand_by_cost: 1.2
      non_constrained:
        p_min_pu: 0.0
        restart_cost: 0
        stand_by_cost: 0
    market_opportunity:
      low:
        vre_cost_factor: 0.8
        battery_cost_factor: 0.8
        h2_cost_factor: 0.8
        sabatier_cost_factor: 0.8
      mid:
        vre_cost_factor: 1.0
        battery_cost_factor: 1.0
        h2_cost_factor: 1.0
        sabatier_cost_factor: 1.0
      high:
        vre_cost_factor: 1.0
        battery_cost_factor: 1.5
        h2_cost_factor: 1.5
        sabatier_cost_factor: 1.5
    employment_transfer:
      unfavorable:
        stand_by_cost_factor: 0.0
      favorable:
        stand_by_cost_factor: 1.0
  current_scenario:
    smelter_flexibility: low
    primary_demand: high
    market_opportunity: low
    employment_transfer: favorable
  al_marginal_cost_storage: 3.79e-05
  al_storage_limit: 8760
snapshots:
  start: '2020-01-01'
  end: '2021-01-01'
  inclusive: left
logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'
enable:
  build_cutout: false
  retrieve_cutout: false
  retrieve_raster: false
atlite:
  nprocesses: 4
  show_progress: true
  cutouts:
    China-2020:
      module: era5
      dx: 0.25
      dy: 0.25
solar_thermal_angle: 45
Technique:
  solar: true
  onwind: true
  offwind: true
coal_cc: true
hydrogen_lines: true
heat_coupling: true
add_gas: true
add_coal: true
add_biomass: true
add_hydro: true
add_H2: true
add_methanation: true
existing_infrastructure:
- coal
- CHP coal
- CHP gas
- OCGT
- solar
- solar thermal
- onwind
- offwind
- coal boiler
- ground heat pump
- nuclear
bus_suffix:
- ''
- ' central heat'
- ' decentral heat'
- ' gas'
- ' coal'
- ' aluminum'
bus_carrier:
  ? ''
  : AC
  ' central heat': heat
  ' decentral heat': heat
  ' gas': gas
  ' coal': coal
  ' aluminum': aluminum
Techs:
  vre_techs:
  - onwind
  - offwind
  - solar
  - solar thermal
  - hydroelectricity
  - nuclear
  - biomass
  - heat pump
  - resistive heater
  - Sabatier
  - H2 CHP
  conv_techs:
  - OCGT gas
  - CHP gas
  - gas boiler
  - coal boiler
  - coal power plant
  - CHP coal
  store_techs:
  - H2
  - battery
  - water tanks
  - PHS
transmission_efficiency:
  DC:
    efficiency_static: 0.98
    efficiency_per_1000km: 0.977
  H2 pipeline:
    efficiency_static: 1
    efficiency_per_1000km: 0.979
    compression_per_1000km: 0.019
chp_parameters:
  eff_el: 0.3978
  eff_th: 0.5304
solar_cf_correction: 0.85
time_dep_hp_cop: true
tes_tau: 3.0
renewable:
  onwind:
    cutout: China-2020
    resource:
      method: wind
      turbine: Vestas_V112_3MW
    capacity_per_sqkm: 3
    potential: simple
    natura: false
    clip_p_max_pu: 0.01
    min_p_nom_max: 0.01
  offwind:
    cutout: China-2020
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_5MW_offshore
    capacity_per_sqkm: 2
    correction_factor: 0.8855
    potential: simple
    natura: true
    max_depth: 50
    clip_p_max_pu: 0.01
    min_p_nom_max: 0.01
  solar:
    cutout: China-2020
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 35.0
        azimuth: 180.0
    capacity_per_sqkm: 5.1
    potential: simple
    correction_factor: 0.85
    natura: false
    clip_p_max_pu: 0.01
    min_p_nom_max: 0.01
electricity:
  voltages:
  - 220.0
  - 300.0
  - 380.0
  co2limit: 77500000.0
  co2base: 1487000000.0
  agg_p_nom_limits: data/agg_p_nom_minmax.csv
  extendable_carriers:
    Generator: []
    StorageUnit: []
    Store:
    - battery
    - H2
    Link:
    - battery
  max_hours:
    battery: 6
    H2: 168
  powerplants_filter: false
  custom_powerplants: false
  conventional_carriers:
  - nuclear
  - oil
  - OCGT
  - CCGT
  - coal
  - lignite
  - geothermal
  - biomass
  renewable_capacities_from_OPSD: []
hydro:
  hydro_capital_cost: true
  PHS_max_hours: 24.0
costs:
  year: 2030
  lifetime: 25
  discountrate: 0.02
  USD2013_to_EUR2013: 0.9189
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.0
    H2: 0.0
    electrolysis: 0.0
    fuel cell: 0.0
    battery: 0.0
    battery inverter: 0.0
  emission_prices:
    co2: 0.0
plot: true
plotting:
  map:
    figsize:
    - 14
    - 8
    boundaries:
    - 71
    - 135.0
    - 0
    - 56.0
    cost_size_factor: 15000000000.0
    bus_size_factor: 100000.0
    linewidth_factor: 6000.0
    bus_size_factor_demand: 20000000.0
    bus_size_factor_heat: 50000.0
    linewidth_factor_heat: 50000.0
  costs_max: 500
  costs_avg: 50
  costs_threshold: 1000
  costs_plots_threshold: 2
  energy_max: 25000.0
  energy_min: 0.0
  energy_threshold: 50.0
  loads:
  - electricity
  - decentral heat
  - central heat
  vre_techs:
  - onwind
  - offwind
  - solar
  conv_techs:
  - gas
  - gas-heat
  - gas-AC
  - AC-gas
  - coal
  - coal-AC
  - solar thermal
  - AC-heat
  - AC-AC
  - stations-AC
  - uranium
  - H2-AC
  - H2-gas
  storage_techs:
  - hydro+PHS
  - battery
  - AC-battery
  - H2
  - AC-H2
  - AC-heat
  tech_colors:
    blank: white
    wind: '#235ebc'
    onwind: '#235ebc'
    onshore wind: '#235ebc'
    offwind: '#6895dd'
    offshore wind: '#6895dd'
    offwind-ac: '#6895dd'
    offshore wind (AC): '#6895dd'
    offshore wind ac: '#6895dd'
    offwind-dc: '#74c6f2'
    offshore wind (DC): '#74c6f2'
    offshore wind dc: '#74c6f2'
    hydro: '#298c81'
    hydro reservoir: '#298c81'
    ror: '#3dbfb0'
    run of river: '#3dbfb0'
    hydroelectricity: '#298c81'
    PHS: '#51dbcc'
    hydro+PHS: '#08ad97'
    wave: '#a7d4cf'
    solar: '#f9d002'
    solar PV: '#f9d002'
    solar thermal: '#ffbf2b'
    residential rural solar thermal: '#f1c069'
    services rural solar thermal: '#eabf61'
    residential urban decentral solar thermal: '#e5bc5a'
    services urban decentral solar thermal: '#dfb953'
    urban central solar thermal: '#d7b24c'
    solar rooftop: '#ffea80'
    OCGT: '#e0986c'
    OCGT marginal: '#e0986c'
    OCGT-heat: '#e0986c'
    gas boiler: '#db6a25'
    gas boilers: '#db6a25'
    gas boiler marginal: '#db6a25'
    residential rural gas boiler: '#d4722e'
    residential urban decentral gas boiler: '#cb7a36'
    services rural gas boiler: '#c4813f'
    services urban decentral gas boiler: '#ba8947'
    urban central gas boiler: '#b0904f'
    gas: '#e05b09'
    fossil gas: '#e05b09'
    natural gas: '#e05b09'
    biogas to gas: '#e36311'
    CCGT: '#a85522'
    CCGT marginal: '#a85522'
    allam: '#B98F76'
    gas for industry co2 to atmosphere: '#692e0a'
    gas for industry co2 to stored: '#8a3400'
    gas for industry: '#853403'
    gas for industry CC: '#692e0a'
    gas pipeline: '#ebbca0'
    gas pipeline new: '#a87c62'
    oil: '#c9c9c9'
    oil boiler: '#adadad'
    residential rural oil boiler: '#a9a9a9'
    services rural oil boiler: '#a5a5a5'
    residential urban decentral oil boiler: '#a1a1a1'
    urban central oil boiler: '#9d9d9d'
    services urban decentral oil boiler: '#999999'
    agriculture machinery oil: '#949494'
    shipping oil: '#808080'
    land transport oil: '#afafaf'
    Nuclear: '#ff8c00'
    Nuclear marginal: '#ff8c00'
    nuclear: '#ff8c00'
    uranium: '#ff8c00'
    Coal: '#545454'
    coal: '#545454'
    coal power plant: '#545454'
    coal boiler: '#787575'
    Coal marginal: '#545454'
    solid: '#545454'
    Lignite: '#826837'
    lignite: '#826837'
    Lignite marginal: '#826837'
    biogas: '#e3d37d'
    biomass: '#baa741'
    biomass CHP: '#baa741'
    solid biomass: '#baa741'
    solid biomass transport: '#baa741'
    solid biomass for industry: '#7a6d26'
    solid biomass for industry CC: '#47411c'
    solid biomass for industry co2 from atmosphere: '#736412'
    solid biomass for industry co2 to stored: '#47411c'
    urban central solid biomass CHP: '#9d9042'
    urban central solid biomass CHP CC: '#6c5d28'
    biomass CHP CC: '#6c5d28'
    biomass carbon capture: '#6c5d28'
    biomass boiler: '#8A9A5B'
    residential rural biomass boiler: '#a1a066'
    residential urban decentral biomass boiler: '#b0b87b'
    services rural biomass boiler: '#c6cf98'
    services urban decentral biomass boiler: '#dde5b5'
    biomass to liquid: '#32CD32'
    BioSNG: '#123456'
    lines: '#6c9459'
    transmission lines: '#6c9459'
    electricity distribution grid: '#97ad8c'
    low voltage: '#97ad8c'
    electric load: '#110d63'
    electric demand: '#110d63'
    electricity: '#110d63'
    industry electricity: '#2d2a66'
    industry new electricity: '#2d2a66'
    agriculture electricity: '#494778'
    battery: '#ace37f'
    battery storage: '#ace37f'
    battery charger: '#88a75b'
    battery discharger: '#5d4e29'
    home battery: '#80c944'
    home battery storage: '#80c944'
    home battery charger: '#5e8032'
    home battery discharger: '#3c5221'
    BEV charger: '#baf238'
    V2G: '#e5ffa8'
    land transport EV: '#baf238'
    Li ion: '#baf238'
    water tanks: '#e69487'
    residential rural water tanks: '#f7b7a3'
    services rural water tanks: '#f3afa3'
    residential urban decentral water tanks: '#f2b2a3'
    services urban decentral water tanks: '#f1b4a4'
    urban central water tanks: '#e9977d'
    hot water storage: '#e69487'
    hot water charging: '#e8998b'
    urban central water tanks charger: '#b57a67'
    residential rural water tanks charger: '#b4887c'
    residential urban decentral water tanks charger: '#b39995'
    services rural water tanks charger: '#b3abb0'
    services urban decentral water tanks charger: '#b3becc'
    hot water discharging: '#e99c8e'
    urban central water tanks discharger: '#b9816e'
    residential rural water tanks discharger: '#ba9685'
    residential urban decentral water tanks discharger: '#baac9e'
    services rural water tanks discharger: '#bbc2b8'
    services urban decentral water tanks discharger: '#bdd8d3'
    heat load: '#cc1f1f'
    heat: '#cc1f1f'
    heat demand: '#cc1f1f'
    rural heat: '#ff5c5c'
    residential rural heat: '#ff7c7c'
    services rural heat: '#ff9c9c'
    central heat: '#cc1f1f'
    urban central heat: '#d15959'
    decentral heat: '#750606'
    residential urban decentral heat: '#a33c3c'
    services urban decentral heat: '#cc1f1f'
    low-temperature heat for industry: '#8f2727'
    process heat: '#ff0000'
    agriculture heat: '#d9a5a5'
    heat pumps: '#2fb537'
    heat pump: '#2fb537'
    air heat pump: '#36eb41'
    residential urban decentral air heat pump: '#48f74f'
    services urban decentral air heat pump: '#5af95d'
    urban central air heat pump: '#6cfb6b'
    ground heat pump: '#2fb537'
    residential rural ground heat pump: '#48f74f'
    services rural ground heat pump: '#5af95d'
    Ambient: '#98eb9d'
    CHP: '#8a5751'
    CHP coal: '#8a5751'
    CHP coal generator: '#8a5751'
    CHP coal boiler: '#8a7f7d'
    urban central gas CHP: '#8f6e6a'
    CHP gas: '#8f6e6a'
    CHP gas generator: '#8f6e6a'
    CHP gas boiler: '#8f6e6a'
    CHP CC: '#634643'
    urban central gas CHP CC: '#6e4e4c'
    CHP heat: '#8a5751'
    CHP electric: '#8a5751'
    district heating: '#e8beac'
    resistive heater: '#d8f9b8'
    residential rural resistive heater: '#bef5b5'
    residential urban decentral resistive heater: '#b2f1a9'
    services rural resistive heater: '#a5ed9d'
    services urban decentral resistive heater: '#98e991'
    urban central resistive heater: '#8cdf85'
    retrofitting: '#8487e8'
    coal carbon capture: '#8487e8'
    coal power plant retrofit: '#8487e8'
    building retrofitting: '#8487e8'
    H2 for industry: '#f073da'
    H2 for shipping: '#ebaee0'
    H2: '#bf13a0'
    hydrogen: '#bf13a0'
    SMR: '#870c71'
    SMR CC: '#4f1745'
    H2 liquefaction: '#d647bd'
    hydrogen storage: '#bf13a0'
    H2 Store: '#bf13a0'
    H2 storage: '#bf13a0'
    land transport fuel cell: '#6b3161'
    H2 pipeline: '#f081dc'
    H2 pipeline retrofitted: '#ba99b5'
    H2 Fuel Cell: '#c251ae'
    H2 fuel cell: '#c251ae'
    H2 CHP: '#c251ae'
    H2 turbine: '#991f83'
    H2 Electrolysis: '#ff29d9'
    H2 electrolysis: '#ff29d9'
    NH3: '#46caf0'
    ammonia: '#46caf0'
    ammonia store: '#00ace0'
    ammonia cracker: '#87d0e6'
    Haber-Bosch: '#076987'
    Sabatier: '#9850ad'
    methanation: '#c44ce6'
    methane: '#c44ce6'
    helmeth: '#e899ff'
    Fischer-Tropsch: '#25c49a'
    liquid: '#25c49a'
    kerosene for aviation: '#a1ffe6'
    naphtha for industry: '#57ebc4'
    methanolisation: '#83d6d5'
    methanol: '#468c8b'
    shipping methanol: '#468c8b'
    CC: '#f29dae'
    CCS: '#f29dae'
    CO2 sequestration: '#f29dae'
    DAC: '#ff5270'
    co2 stored: '#f2385a'
    co2: '#f29dae'
    co2 vent: '#ffd4dc'
    CO2 pipeline: '#f5627f'
    process emissions CC: '#000000'
    process emissions: '#222222'
    process emissions to stored: '#444444'
    process emissions to atmosphere: '#888888'
    oil emissions: '#aaaaaa'
    shipping oil emissions: '#555555'
    shipping methanol emissions: '#666666'
    land transport oil emissions: '#777777'
    agriculture machinery oil emissions: '#333333'
    shipping: '#03a2ff'
    power-to-heat: '#2fb537'
    power-to-gas: '#c44ce6'
    power-to-H2: '#ff29d9'
    power-to-liquid: '#25c49a'
    gas-to-power/heat: '#ee8340'
    coal-to-heat: '#545454'
    waste: '#e3d37d'
    other: '#000000'
    geothermal: '#ba91b1'
    AC: '#70af1d'
    AC-AC: '#70af1d'
    AC line: '#70af1d'
    links: '#8a1caf'
    HVDC links: '#8a1caf'
    DC: '#8a1caf'
    DC-DC: '#8a1caf'
    DC link: '#8a1caf'
    aluminum: '#8B4513'
    aluminum smelter: '#8B4513'
    aluminum storage: '#D2691E'
  nice_names:
    AC-AC: Electric grid
    H2-AC: H2 Fuel Cell
    AC-H2: H2 Electrolysis
    H2-gas: Sabatier + DAC
    AC-battery: Battery Charger
    CHP: Combined Heat and Power
    OCGT: Open-Cycle Gas
    CCGT: Combined-Cycle Gas
    offwind: Offshore Wind
    onwind: Onshore Wind
    solar: Solar
    coal: Coal Power Plant
    coal-AC: Combined Heat and Power
    coal-heat: Coal Boiler
    gas-AC: Open-Cycle Gas
    PHS: Pumped Hydro Storage
    stations-AC: Reservoir & Dam
    hydro: Reservoir & Dam
    battery: Battery Storage
    H2: Hydrogen Storage
    lines: Transmission Lines
    ror: Run of River
    AC-heat: Heat Pump
    heat pump: Heat Pump
    solar thermal: Solar Thermal
    uranium: Nuclear
    aluminum: Aluminum Smelter
    aluminum smelter: Aluminum Smelter
    aluminum storage: Aluminum Storage
    energy:
      coal: Coal
      offwind: Offshore Wind
      onwind: Onshore Wind
      solar: Solar
      solar thermal: Solar Thermal
no_lines: false
line_volume_limit_max: 5000000000000000.0
line_cost_factor: 1
existing_capacities:
  grouping_years:
  - 1980
  - 1985
  - 1990
  - 1995
  - 2000
  - 2005
  - 2010
  - 2015
  - 2019
  - 2020
  - 2025
  - 2030
  - 2035
  - 2040
  - 2045
  - 2050
  - 2055
  - 2060
  threshold_capacity: 1
